# Generated by Django 3.2.9 on 2021-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20211115_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
