# Generated by Django 3.2.9 on 2021-11-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20211115_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.idea')),
            ],
        ),
    ]
